### ISSUE TITLE
Vacation merssage in GO, can't save vacation message

### ISSUE THREAD

**Issue by flaviozluca** [polarismail/Webmail#10]
Friends,

Issue remains. I know you're aware, just to keep registered. I had a case already of user trying to use it and it failing.

Http error 500.

original issue (there it shows as solved):
https://github.com/polarismail/Webmail/issues/5

Thanks.

**Comment by flaviozluca** [comment]
Friend,

We updated Go yesterday to latest.

I reforwarded messages to test.

Message 1 issue seems ok but message2 issue remains.

Can you test message2 case, pls? Mercadolivre.

Thanks

**Comment by dana-b** [comment]
Hi Flavio,

The issue has been fixed. Please check and let us know.

Best,
Dana

**Comment by flaviozluca** [comment]
Dear Dana,

Thanks. It worked.

I wrote, in flavio@lucanet.com.br

"Email recebido.

Agradeço".

It worked fine, I received it fine in Gmail.

Then, I went back to disable the autoresponder in GO and the accent was messed up.

See: 

![image](https://user-images.githubusercontent.com/44004645/139068536-c3ebf7b0-3d73-41bc-9749-6af81c88adfb.png)

**Comment by polarismail** [comment]
Fixed, please check again now

**Comment by flaviozluca** [comment]
Strange, another problem now. It says I informed an invalid value for "Enabled" (habilitado), as if it's not accepting YES.

See

![image](https://user-images.githubusercontent.com/44004645/139122753-8f440e8a-3d69-462a-953c-3ea83ed1e8ab.png)

**Comment by gtech99** [comment]
The error needs to be a bit more clear indeed. You haven't specified an end-date

**Comment by flaviozluca** [comment]
Even specifying end date, same error. Feel free to test in my account.

**Comment by polarismail** [comment]
cleaned up the code a bit and made the error more user friendly, please check again

**Comment by flaviozluca** [comment]
Thanks, now it's fine. I see the default is no end date, which means indefinite, correct?

Just 1 note, but I guess nothing can be done about it, the 2 save buttons might be a bit confusing, 1 for this option and another one for the GO interface.

can close.

Thanks.

**Comment by dana-b** [comment]
The save button of GO is deactivated, only the save vacation message will work.

Closing issue.
