### ISSUE TITLE
auto-responder formatting

### ISSUE THREAD

**Issue by flaviozluca** [polarismail/Webmail#11]
Friends,

suporte@lucanet.com.br.

So, I went to try to edit an autoresponder via user panel,  I keep getting invalid date, untrue. See https://www.screenpresso.com/=B6OBg

Then I tried via Webmail and I noticed formatting is different. It's not respecting the line feeds. See https://www.screenpresso.com/=OMq6f

Thanks

**Comment by polarismail** [comment]
Hi Flavio, please keep it one issue per issue ticket, it makes it much easier to follow up

issue #1: fixed
issue #2: this one depends on GO, they are formatting it a bit special. I have a ticket opened with them

**Comment by flaviozluca** [comment]
Sorry. I thought #1 wasnt an issue, rather because user panel was gonna be retired soon. Sorry, anyway, next time Ill do 1 per item.

If I edit inside GO, it will break formatting, right?

Thanks.

**Comment by polarismail** [comment]
GO line formatting has been fixed for vacation messages

**Comment by flaviozluca** [comment]
Thanks. Confirmed.
