### ISSUE TITLE
Issue with icons up top, in inbox

### ISSUE THREAD

**Issue by flaviozluca** [polarismail/Webmail#18]
Friend,

When you reduce the size of the pane, the icons start to disappear (search, etc.), but the 3 vertical dots, which contains all of icons that disappear when you reduce the pane, should always remain.

That happens in GO's demo [demo.](https://demo.groupoffice.net/), but in our webmail, sometimes it truly disappears, although it's clickable.

https://user-images.githubusercontent.com/44004645/210624416-1447cc32-7daf-44b8-bdfd-1dc80c363d14.mp4

This is shown in the attached video.

So, IMHO, this is an issue.

However, I also opened a feature request with GO, as we believe this could be improved, in general, regarding what happens when you reduce the pane. Here's the FR I opened there: https://github.com/Intermesh/groupoffice/issues/947

**Comment by polarismail** [comment]
GO already fixed this in a more recent version by setting a minimum width for that panel

**Comment by flaviozluca** [comment]
But they did it so just to avoid someone closing it completely, AFAIR, no? Which was that case of "disappearing emails". It was something else.

**Comment by polarismail** [comment]
setting a minimum width field ensures that all icons are in view

**Comment by flaviozluca** [comment]
He had told us "I set a min width of 300 px. on the panel. Hope this helps."

I will test again when you upgrade GO. pls tell me when you upgrade, Ok? Thanks.

In any way, I still this this is a good suggestion: https://github.com/Intermesh/groupoffice/issues/947

**Comment by polarismail** [comment]
I am confused, so you are saying that 300 px is not enough which is why you opened this ticket with us/them ?

**Comment by flaviozluca** [comment]
It's separate cases.

The issue they fixed was about emails that disappeared, remember? The user would close the pane so much that no email would appear. They thought emails disappeared. You knew about the issue. So Merijn said he put a minimum width for the next release, to avoid this.

This ticket is something else. About the fact that, only in our GO (and not in GO's own demo), as you reduce the size of the pane, the 3 vertical dots (which contains the icons that disappear as you lower the width, example: search icons, refresh, trash, etc.) ends up, at some point, not appearing at all. Disappears. This happens only in our GO and we show it in the video.

**Comment by polarismail** [comment]
Why do you think it's a separate case, still ? 

I already mentioned that it's the **same issue** , and that GO fixed it in a more recent version.
You even saw it's fixed in their online demo.

What am I missing here ?

**Comment by flaviozluca** [comment]
Ah, Ok. Then I misunderstood. Sorry.

In any way, my FR remains with them. Thanks.
