### ISSUE TITLE
Buttons in Firefox strange

### ISSUE THREAD

**Issue by flaviozluca** [polarismail/Webmail#4]
GO's buttons appear with the color of "mouseover" and remain that way for longer time than expected.

Cleared cache, reset grids, same thing.

I went to test GO DEMO, there it doesnt happen.

https://user-images.githubusercontent.com/44004645/117363770-69008780-ae93-11eb-9b7d-060c87ce1c59.mp4

https://user-images.githubusercontent.com/44004645/117363771-69991e00-ae93-11eb-95e8-cfc9b9d6bea0.mp4

In Chrome it doesnt happen in our install, but the SEND button becomes a bit too dark when clicking send.

**Comment by polarismail** [comment]
Unable to replicate in Firefox, it works as expected. Please try on a different computer

**Comment by polarismail** [comment]
No further updates, closing ticket
