### ISSUE TITLE
Error sending mail using email from contacts (urgent)

### ISSUE THREAD

**Issue by flaviozluca** [polarismail/Webmail#8]
A customer contacted us a bit urgent

 this error occurs when he sents to users from his address book only, clicking on address books, inside contacts, then on the right side, in contact's email link (where there are all fields shown, phone, name, email).

![image](https://user-images.githubusercontent.com/44004645/117967597-9b7b0c00-b2fb-11eb-9814-fbc6e405d04b.png)

I then found it happens with everyone, even inside my login.

I told him to copy x paste addresses for now or type them, instead.

Holy cow, found out this is more serious then we think. Even via autofill it's broken! Just confirmed in my account, it also happens.

Thanks

**Comment by polarismail** [comment]
I am unable to replicate this in your account by going to AB and clicking on the e-mail of a contact. It properly opens up the compose dialog with the e-mail in it.

Which contact are you using ?

**Comment by flaviozluca** [comment]
Fixed in next GO release, as per you informed.

**Comment by polarismail** [comment]
is this still an issue ?

**Comment by flaviozluca** [comment]
Strange why this remained open, I remember we having discussed it had been solved long ago.

Thanks,
